const state={tab:'home',budget:60,cycle:true,query:'',meals:[
{id:1,type:'Frühstück',name:'Protein Porridge',kcal:390,protein:27,done:true,ingredients:'Haferflocken, Skyr, Beeren, Nüsse'},
{id:2,type:'Mittagessen',name:'Chicken Caesar Wrap',kcal:520,protein:42,done:true,ingredients:'Hähnchen, Salat, Parmesan, Joghurtdressing'},
{id:3,type:'Abendessen',name:'Creamy Tomato Protein Pasta',kcal:610,protein:45,done:false,ingredients:'Vollkornnudeln, Hähnchen, Tomaten, Spinat'},
{id:4,type:'Snack',name:'Skyr Bowl',kcal:180,protein:19,done:false,ingredients:'Skyr, Beeren, Honig, Mandeln'}],
items:[['Hähnchenbrust','600 g',6.49],['Skyr','1 kg',2.78],['Wraps','1 Packung',1.99],['Vollkornnudeln','500 g',1.29],['Tomaten','500 g',2.49],['Blattspinat','300 g',1.79],['Beeren','400 g',3.99],['Haferflocken','500 g',0.99],['Parmesan','150 g',2.99],['Salat','1 Kopf',1.49],['Mandeln','200 g',2.49],['Joghurt','500 g',1.19]].map((x,i)=>({id:i+1,name:x[0],amount:x[1],price:x[2],checked:i<2}))};
const app=document.getElementById('app');
const euro=n=>n.toFixed(2).replace('.',',')+' €';
const eaten=()=>state.meals.filter(m=>m.done).reduce((s,m)=>s+m.kcal,0);
const protein=()=>state.meals.filter(m=>m.done).reduce((s,m)=>s+m.protein,0);
const shopTotal=()=>state.items.reduce((s,i)=>s+i.price,0);
const emoji=t=>t==='Frühstück'?'🥣':t==='Mittagessen'?'🌯':t==='Abendessen'?'🍝':t==='Snack'?'🫐':'🍽️';
function mealCard(m){return `<div class="meal-card ${m.done?'done':''}"><div class="meal-emoji">${emoji(m.type)}</div><div class="meal-copy"><small>${m.type}</small><strong>${m.name}</strong><span>${m.ingredients}</span></div><div class="meal-meta"><b>${m.kcal} kcal</b><button class="check-btn ${m.done?'checked':''}" data-meal="${m.id}">${m.done?'✓':''}</button></div></div>`}
function home(){return `<section class="screen"><div class="hero"><div><p class="eyebrow">DIENSTAG, 18. AUGUST</p><h2>Guten Morgen, Annabelle ☀️</h2><p>Dein Tag ist geplant. Du kannst alles flexibel anpassen.</p></div><div class="avatar">A</div></div><div class="stats-grid">
${stat('👣','3.842','/ 8.000','Schritte')}${stat('🔥',eaten(),'/ 1.750','kcal')}${stat('💪',protein(),'/ 105 g','Protein')}${stat('🌙','7 h 34','min','Schlaf')}</div>
${state.cycle?`<div class="cycle-card"><div class="cycle-icon">✿</div><div><strong>Zyklus • Tag 24</strong><span>Lutealphase</span><p>Heute: einfache, sättigende Mahlzeiten und ausreichend Flüssigkeit einplanen.</p></div><b>›</b></div>`:''}
<div class="section-title"><div><p class="eyebrow">HEUTE</p><h3>Dein Essensplan</h3></div><strong>${Math.max(0,1750-eaten())} kcal übrig</strong></div><div class="meal-list">${state.meals.map(mealCard).join('')}</div>
<div class="shop-banner"><span>🛒</span><div><small>Wocheneinkauf</small><strong>REWE · ${euro(shopTotal())}</strong><span>unter deinem 60-€-Budget</span></div><b>›</b></div><div class="insight-card"><span>✨</span><div><strong>NOURA Insight</strong><p>Du hast deine geplanten Mahlzeiten diese Woche bisher zu 80 % eingehalten. Gute Basis für eine stabile Routine.</p></div></div></section>`}
function stat(i,v,s,l){return `<div class="stat-card"><div class="icon-bubble">${i}</div><strong>${v}</strong><span>${s}</span><small>${l}</small></div>`}
function plan(){return `<section class="screen"><div class="page-head"><div><p class="eyebrow">WOCHENPLAN</p><h2>Dein Plan</h2></div><b>▣</b></div><div class="week-row">${['Mo','Di','Mi','Do','Fr','Sa','So'].map((d,i)=>`<div class="day-pill ${i===1?'active':''}"><span>${d}</span><b>${17+i}</b></div>`).join('')}</div><div class="summary-card"><div><small>Tagesziel</small><strong>1.750 kcal</strong></div><div><small>Protein</small><strong>105 g</strong></div><div><small>Budget/Tag</small><strong>8,57 €</strong></div></div><div class="meal-list">${state.meals.map(mealCard).join('')}</div><button class="primary-btn">✨ Plan automatisch optimieren</button></section>`}
function track(){return `<section class="screen"><div class="page-head"><div><p class="eyebrow">TRACKING</p><h2>Essen eintragen</h2></div><b>＋</b></div><div class="track-card"><label>Lebensmittel / Gericht<input id="foodName" placeholder="z. B. Banane"></label><div class="field-grid"><label>Kalorien<input id="foodKcal" type="number" placeholder="120"></label><label>Protein (g)<input id="foodProtein" type="number" placeholder="2"></label></div><button id="addFood" class="primary-btn">＋ Hinzufügen</button></div><div class="ai-card"><span>✨</span><div><strong>Später: Foto- & Barcode-Scan</strong><p>In diesem MVP ist das Tracking manuell. Echte KI- und Scanner-Funktionen können später ergänzt werden.</p></div></div><div class="meal-list">${state.meals.filter(m=>m.type==='Zusätzlich').map(m=>mealCard(m)).join('')}</div></section>`}
function shop(){let diff=state.budget-shopTotal();let filtered=state.items.filter(i=>i.name.toLowerCase().includes(state.query.toLowerCase()));return `<section class="screen"><div class="page-head"><div><p class="eyebrow">SUPERMARKT</p><h2>Dein REWE-Einkauf</h2></div><b>🛒</b></div><div class="budget-card"><div><span>💳</span><div><small>Wochenbudget</small><strong>${state.budget} €</strong></div></div><input id="budget" type="range" min="30" max="120" value="${state.budget}"><p class="${diff>=0?'good':'bad'}">${diff>=0?euro(diff)+' übrig':euro(Math.abs(diff))+' über Budget'}</p></div><div class="search"><span>⌕</span><input id="search" value="${state.query}" placeholder="Einkauf durchsuchen"></div><div class="shop-list">${filtered.map(i=>`<button class="shop-item ${i.checked?'checked':''}" data-item="${i.id}"><span class="shop-check">${i.checked?'✓':''}</span><div><strong>${i.name}</strong><small>${i.amount}</small></div><b>${euro(i.price)}</b></button>`).join('')}</div><div class="shop-total"><span>Geschätzter Gesamtpreis</span><strong>${euro(shopTotal())}</strong></div><div class="saving-card"><span>🌿</span><div><strong>9,46 € potenzielle Ersparnis</strong><p>Mock-Daten für Angebote. Echte Filialpreise benötigen später eine Datenquelle oder Partner-API.</p></div></div></section>`}
function profile(){return `<section class="screen"><div class="page-head"><div><p class="eyebrow">PROFIL</p><h2>Annabelle</h2></div><b>⚙️</b></div><div class="profile-card"><div class="big-avatar">A</div><div><strong>Mein Ziel: ausgewogen essen</strong><span>1.750 kcal · 105 g Protein</span><small>Bevorzugter Supermarkt: REWE</small></div></div><div class="settings-list">${setting('🍎','Ernährung','Alles · proteinreich · max. 25 Min.')}${setting('👣','Aktivität','8.000 Schritte pro Tag')}${setting('🌙','Schlaf','Apple Health Verbindung geplant')}<button id="cycleToggle" class="setting-row"><div class="setting-icon">♡</div><div><strong>Zyklus berücksichtigen</strong><span>Optionale Personalisierung</span></div><span class="switch ${state.cycle?'on':''}"><i></i></span></button>${setting('💧','Wasser','Ziel: 2,5 l pro Tag')}</div><div class="privacy-card"><strong>Datenschutz zuerst</strong><p>Dieses MVP speichert nur im Browserzustand und sendet keine Gesundheitsdaten an einen Server.</p></div></section>`}
function setting(i,t,x){return `<div class="setting-row"><div class="setting-icon">${i}</div><div><strong>${t}</strong><span>${x}</span></div><b>›</b></div>`}
function render(){app.innerHTML=({home,plan,track,shop,profile}[state.tab])();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));bind()}
function bind(){document.querySelectorAll('[data-meal]').forEach(b=>b.onclick=()=>{let m=state.meals.find(x=>x.id==b.dataset.meal);m.done=!m.done;render()});document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{let i=state.items.find(x=>x.id==b.dataset.item);i.checked=!i.checked;render()});let a=document.getElementById('addFood');if(a)a.onclick=()=>{let n=document.getElementById('foodName').value.trim(),k=+document.getElementById('foodKcal').value,p=+document.getElementById('foodProtein').value;if(!n||!k)return;state.meals.push({id:Date.now(),type:'Zusätzlich',name:n,kcal:k,protein:p||0,done:true,ingredients:'Manuell eingetragen'});render()};let s=document.getElementById('search');if(s)s.oninput=e=>{state.query=e.target.value;app.innerHTML=shop();bind()};let bd=document.getElementById('budget');if(bd)bd.oninput=e=>{state.budget=+e.target.value;app.innerHTML=shop();bind()};let c=document.getElementById('cycleToggle');if(c)c.onclick=()=>{state.cycle=!state.cycle;render()}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});render();
